### PR TITLE
added scalarization for X and Y

### PR DESCRIPTION
**Pull request by hurricane642**

### CODE REVIEW

**Comment by rosecers** [comment]
> _No description provided._

Oy, where is your summary?

**Review by rosecers — COMMENTED** [review]
A bit of an issue here -- whenever we fit a model and transform the inputs (`X` and `Y`), we must use the *exact same* scaler to transform the out-of-sample data (testing data). In other words, when you fit and scale the X/Y, you have to save the scaler to use when you do transform. Otherwise the model will center the testing data with respect to itself, which will give a bad model.

**Comment by hurricane642** [comment]
Yes, I agree, it's really a problem. I think about it.

**Comment by ceriottm** [comment]
So, in a sklearn context these "composite models" are built by stacking
multiple transformers. I think if you look in the preprocessing section of
their docs there's plenty of examples.
So I'd be against having the scaling as an option to the various tools. IDK
if this was even being discussed, just saying

**Comment by hurricane642** [comment]
That is, it is better to remove any scalarization in principle and process only the data that is transmitted?

**Comment by ceriottm** [comment]
what do you mean with "scalarization"? you mean scaling and centering?

**Comment by hurricane642** [comment]
Yes, exactly

**Comment by ceriottm** [comment]
OK just to agree on nomenclature, usually we refer to that as
"standardization".
I think (but it should be *you* who is aware of the "sklearn way", so
correct me if I'm wrong) that usually the sklearn approach is not to have
options to the transformers that choose whether to apply transformations to
the inputs, but to stack transformers.
I think we should stick to the style, which means changing a bit the way we
do things.

**Comment by hurricane642** [comment]
Do you mean by stacking transformers their phased use in the program itself? Well, that is, in other words, standardization is separate and training is separate.

**Comment by ceriottm** [comment]
Yes.
See
https://scikit-learn.org/stable/modules/preprocessing.html
for an overview, and something like this
https://scikit-learn.org/stable/modules/compose.html#combining-estimators
for stacking a preprocessor and a transformer.

**Comment by rosecers** [comment]
@hurricane642 is this PR redundant with the PR on sklearn-cosmo? If so, can you close?

**Pull request closed without merging**
